//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoSoKTPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CtDonHangs = new HashSet<CtDonHang>();
        }
    
        public string SoDH { get; set; }
        public string MaKH { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<bool> DaKichHoat { get; set; }
        public Nullable<System.DateTime> NgayGH { get; set; }
        public string DiaChiGH { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDonHang> CtDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
