//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoSoKTPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CtDonHangs = new HashSet<CtDonHang>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string HinhDD { get; set; }
        public string NdTomTat { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public int MaLoai { get; set; }
        public string NoiDung { get; set; }
        public string TaiKhoan { get; set; }
        public string DVT { get; set; }
        public Nullable<bool> DaDuyet { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public string NhaSanXuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDonHang> CtDonHangs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
